# Building an R operator app: walkthrough example

Here we will learn through a concrete example how to create an R operator to perform a linear regression.

## Designing the operator {-}

The first step is to define our input projection and output relation. Remember that each operator works on table:

> "Table in, table out!"

Here we want to perform the linear regression of y against x in per cell. Our input is simple.

* x axis
* y axis
* row ID
* column ID

As a starting point, we will output the interecept and the slope of the model.

* 

## Setting up the project {-}

Make sure that tercen-studio is properly set up (Chapter 2) and that both Tercen and RStudio run locally (respectively on http://127.0.0.1:5402 and http://127.0.0.1:8787/).

**1. Cloning the template repository**

Get the template from GitHub.
In RStudio server, File > New project > Version control.
URL: https://github.com/tercen/templateR_operator

Then, I have a new project at the root of my working directory.

**2. Resetting versioning and packrat**

Rename the files.
Reset the versioning and packrat.

## Coding and testing the operator locally {-}

Coming soon.

* How an operator looks like

* Code description

```r
library(tercen)
library(dplyr)

do.lm <- function(df) {
  
  out <- data.frame(
    .ri = df$.ri[1],
    .ci = df$.ci[1],
    intercept = NaN,
    slope = NaN,
    fit.y = rep(NaN, 2),
    fit.x = rep(NaN, 2)
  )
  
  mod <- try(lm(.y ~ .x, data = df))
  
  if(!inherits(mod, 'try-error')) {
    out$intercept <- mod$coefficients[1]
    out$slope <- mod$coefficients[2]
    out$fit.y <- range(mod$fitted.values)
    out$fit.x <- range(df$.x)
  }
  return(out)
  
}

(ctx <- tercenCtx())  %>% 
  select(.x, .y, .ri, .ci) %>% 
  group_by(.ri, .ci) %>%
  do(do.lm(.)) %>%
  ctx$addNamespace() %>%
  ctx$save()
```

Implementing the following sanity checks is recommended when creating an operator:

* check the presence of expected inputs (here, x and y axes)

* add a try function to test the main function implemented (here, `lm`)

**Test in tercen**

## Documenting the operator {-}

Edit the README.md to describe the operator design and usage. The documentation should contain:

* A __general description__ of the operator

* A description of the __input projections__

* A description of the __output relations__

For example, here is how the `lm` operator documentation looks:

**Description**

The `lm` operator performs a linear regression in Tercen.

**Usage**

Input projection|.
---|---
`y-axis`| measurement value
`x-axis`| explanatory value

Output relations|.
---|---
`intercept`| numeric, p-value calculated per cell
`slope`| numeric, p-value calculated per cell
`fit.x`| numeric, lowest and highest x values
`fit.y`| numeric, lowest and highest predicted y values

**Details**

The `lm` operator performs a linear regression on each cell.

**References**

See [Linear regression on Wikipedia](https://en.wikipedia.org/wiki/Linear_regression) and
`lm` [R function documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm).

**See Also**

[anova](https://github.com/tercen/anova_operator)


## Deploying the operator {-}

**main.R**

Once you are confident enough that your operator is working after testing it locally, you can copy the code to the `main.R` file, ignoring the local stuff.

**Init renv**

The ability to run an operator with exactly the same packages you used when you developed is essential for reproducible science. In order to ensure reproducibility, you can associate packages and their versions to your operator by using the `init()` function of the `renv` package: 

```r
renv::init()
```

This will initiate a project-local environment with a private R library in the `renv` subdirectory.

**Unit test**

Coming soon.

```r
# Simulate tercen input based on the CO2 dataset 
# with an x and y-axis, rows and columns
data(CO2)
df <- data.frame(.x = CO2$conc, .y = CO2$uptake, .ri = CO2$Plant, .ci = CO2$Treatment)

# Run the do.lm() function to generate the expected output
out <- df %>% select(.ci, .ri, .x, .y) %>%
  group_by(.ri, .ci) %>%
  do(do.lm(.))

# write input and expected output in the test subdirectory
write.csv(CO2, file="./test/CO2.csv", row.names = FALSE, quote = FALSE)
write.csv(out, file="./test/output.csv", row.names = FALSE, quote = FALSE)
```

**Create and push repository**

Coming soon.

**Notify community**

Currently, we ask you to send an email to info@tercen.com containing the description and link to the __operators app__ git repository, Tercen support will manually test it and add it to the __app-library__ and thus allowing others to access it. We are currently building an web entry point for researchers to browse all the apps offered by the community.
