# CI and Github Actions

## Test not found

`operator.run.test.not.found`

This error happens when none of the `test`, `tests` or `workflow_tests` have been found at the repository root.

## Wrong relations

`task.test.operator.bad.nRelations`

This error happens when there are not as many tables (relations) between the computed and expected outputs.

## Wrong nCols / nRows

`task.test.operator.bad.nCols` 
`task.test.operator.bad.nRows`

This error happens when there are not as many columns or rows between the computed and expected output relations.

## Wrong column names

`task.test.operator.bad.column.names`

This error happens when the computed and expected output relations do not have the exact same column names.

Maybe you've added or renamed a column in the latest version of the operator? In that case, the reference table should be updated accordingly.

## Wrong column type

`task.test.operator.bad.column.type`

* Check that .ri and .ci factors are output as integers in your operators.
* If another factor (for example, a cluster ID), tercen test will expect is to be
a double. In that case, you need to provide a schema file. If you use
tim to genenerate your test, you can use the XXX argument to the build_test_data 
function.

<!-- Examples: -->
<!-- * X operator -->
<!-- * X operator, ci and ri -->

### Wrong values

`task.test.operator.bad.value`

This error occurs when a value is different between the reference table and 
the computed table. It gives you the row number and both values to help
finding the issue.

### Wrong correlation

`task.test.operator.bad.correlation`

This error occurs when the correlation between the reference table and 
the computed table values is not high enough.

### Untrusted git

`tercen.forbidden.untrusted.git`

This error occurs when you try to install an operator from an untrusted GitHub organisation. The organisation in which you develop your operator
should be added to your Tercen instance configuration file.