project:
  type: book
  output-dir: "_site"

book:
  title: "Tercen Developer's Guide"
  author: "The Tercen Team"
  description: "How to develop operators and apps for Tercen."
  repo-url: https://github.com/tercen/developers_guide
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    
    - part: "Getting Started"
      chapters:
        - 01-getting-started/0-intro_guidelines.qmd
        - 01-getting-started/1-core-concepts.qmd
        - 01-getting-started/2-environment-setup.qmd
    
    - part: "Operator Development"
      chapters:
        - 02-operator-development/1-design-principles.qmd
        - 02-operator-development/2-repository-setup.qmd
        - 02-operator-development/3-development-environment.qmd
        - 02-operator-development/4-basic-implementation.qmd
        - 02-operator-development/5-advanced-features.qmd
        - 02-operator-development/6-operator-specifications.qmd
        - 02-operator-development/7-documentation-deployment.qmd
        - 02-operator-development/8-ci.qmd
        - 02-operator-development/9-installation.qmd
        - 02-operator-development/10-input-output-patterns.qmd
        - 02-operator-development/11-operator-improvements.qmd
    
    - part: "Workflow Template Development"
      chapters:
        - 03-workflow-templates/1-templates.qmd
        - 03-workflow-templates/2-templates-ci.qmd
        - 03-workflow-templates/3-templates-installation.qmd

    - part: "Advanced Topics"
      chapters:
        - 04-advanced-topics/1-patterns-plots.qmd
        - 04-advanced-topics/2-tercen-cli.qmd
        - 04-advanced-topics/3-gpu-development.qmd
        
    - part: "Troubleshooting"
      chapters:
        - 05-troubleshooting/1-common-issues.qmd
        - 05-troubleshooting/2-ci.qmd
    
    - part: "Appendices"
      chapters:
        - 99-appendices/1-glossary.qmd
        - 99-appendices/2-organisation-setup.qmd
        - 99-appendices/3-tercen-studio.qmd

format:
  html:
    theme: 
      - cosmo
    css: style.css
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    code-fold: false
    code-tools: true
    search: true

csl: https://www.zotero.org/styles/apa
