# Appendix {.unnumbered}

# Glossary {-}

__App__:
A small workflow composed of __steps__, visuals and __operators__. Typically it 
achieves one task, e.g. PCA app. The PCA app is composed of one result visual 
and one computation and one data wrangling step.

__Cross-tab view__:
A Tercen interface window to define a projection view (i.e. what is on the: 
row, col, y-axis, x-axis, color, label).

__Library__:
A repository of Tercen __modules__.

__Long format__:
A format where every row is a measurement.

__Measurement__: A numerical variable

__Module__:
A plug-in to Tercen. It can be an __operator__, __app__, or __template__. 

__Observation__: An observation is the factor name given to a value (measurement), 
at a particular moment in time, of a particular variable.

__Operator__:
An operator computes on data supplied to it by the __projection__ view defined using the __cross-tab window__.

__Projection__:
A projection is defined using the __cross-tab window__.

__Step__:
A single step allows for a visual __projection__ and optionally a 
computation using an __operator__.

__Template__:
A templatised __workflow__.

__Variable__: A variable is a characteristic of a unit being observed that may 
assume more than one of a set of values to which a numerical measure or a 
category from a classification can be assigned (e.g. income, age, weight, etc., 
and “occupation”, “industry”, “disease”, etc.

__Wide format__:
A format where every column is a variable.

__Workflow__:
A sequence of __steps__ or __apps__ to achieve an analysis pipeline.
