on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Render and Publish Quarto Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install jupyter

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: book
          to: html

      - name: Check render output
        run: |
          echo "Checking if _site directory was created..."
          ls -la book/_site/
          echo "Checking if index.html exists..."
          test -f book/_site/index.html && echo "✅ index.html found" || echo "❌ index.html not found"

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        if: contains(github.ref, 'master')
        with:
          path: source/_site

      - name: Deploy to GitHub Pages
        id: deployment
        if: contains(github.ref, 'master')
        uses: actions/deploy-pages@v2
